[programs.localnet]
anchorapp = "2wvgLFRzyCj7hgGK194omXopF5g9C5JzFYo4fLgpocsY"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Volumes/samsung1TB/web3/sol_earp/wallet_solana/devnet/devnet_auth.json"

[scripts]
test = "mocha -t 1000000 tests/"
