[programs.localnet]
anchorapp = "2wvgLFRzyCj7hgGK194omXopF5g9C5JzFYo4fLgpocsY"
publishincentive = "pvr1XUXRXAzddCecgyvMxb88NZsAXh69d4uRdsyc1Kf"
disbursereward = "ATsznkhxzb6yaGpLGNYeVtkhCaWtJysbDv4NwzAkRnsf"
vault = "DwRPVvFn8a2AqXv8skZxJRp2PRrUqEq9mDzJ7CBaBqKo"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/ashu/.config/solana/devnet.json"

[scripts]
test = "mocha -t 1000000 tests/"
